version: '3'
services:
 db:
   image: mysql:latest
   container_name: mysql_db
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=admin123
     - MYSQL_DATABASE=assignment
   volumes:
     - C:\Users\Mario\Desktop\assignment\assignment\prisma\db:/var/lib/mysql